### ISSUE TITLE
It takes too long.

### ISSUE THREAD

**Issue by openthingsaz** [tchapi/Adafruit-GFX-Font-Customiser#13]
Hello ^^
This project is the best.
However, if the content increases
It takes too long.
It seems to stop when there are many glyphs.
Here is what I used.
Why? Is it stopping?

[BMHANNAPro8.zip](https://github.com/tchapi/Adafruit-GFX-Font-Customiser/files/4829479/BMHANNAPro8.zip)

**Comment by tchapi** [comment]
Hi
Well your file is 3,3M (!) ... and includes non-printable glyphs (_a lot of them_) so your browser cannot process that much.
Obviously this tool is not aimed at non-printables, so remove them from your file, reduce the file size and retry.
