### ISSUE TITLE
Show pixels as squares

### ISSUE THREAD

**Issue by arnoson** [tchapi/Adafruit-GFX-Font-Customiser#21]
Thanks for this awesome tool! Right now the pixels are not displayed as squares but as rectangles. Is there any option to enable this?

**Comment by tchapi** [comment]
Hi @arnoson 

It's unfortunately due to how the "pixels" are rendered in the page (i.e. by a good old table) right now. So the "squareness" of the pixels is basically linked to the width of your window.

There surely is a better way to render this properly, but I haven't taken the time to dig deep into that for now.

Happy to review a PR if you have the time !
Best

**Comment by arnoson** [comment]
okay, I'll have a look if I find some time!

**Comment by tchapi** [comment]
In fact I'm on it :)

**Comment by tchapi** [comment]
Hi again @arnoson,

Do you think you could test https://github.com/tchapi/Adafruit-GFX-Font-Customiser/tree/feature/square-pixels to see if I haven't missed anything or introduced a regression ?

Thanks !

**Comment by arnoson** [comment]
Cool thanks! I tested it with a custom font. The pixels are perfect squares :) but unfortunately wide glyphs get cropped
![Screenshot 2021-03-23 193722](https://user-images.githubusercontent.com/15122993/112200464-8c3ae480-8c0f-11eb-9363-8e6ba98b8982.png)

**Comment by tchapi** [comment]
Hmmm .. yeah, this is the responsive thing again. Ok, I'll work something out for big fonts tomorrow !

**Comment by tchapi** [comment]
Could you send me this custom font @arnoson  ?

**Comment by arnoson** [comment]
sorry had no time, will send it tomorrow! Can I send it as a PM? It's the font of a friend I'm not shure if he's okay with it if I upload it here

**Comment by tchapi** [comment]
sure — tchap at tchap dot me

**Comment by tchapi** [comment]
Received, tested — it works great. I'll merge the branch now.

_PS: Rest assured that I removed all files of the font you sent me from my machines and used it only for testing purposes_

**Comment by arnoson** [comment]
Finally I could test it and it works perfectly! Many thanks for your efforts
