### ISSUE TITLE
unescaped \ in comment -> exported file is not valid

### ISSUE THREAD

**Issue by petrbrouzda** [tchapi/Adafruit-GFX-Font-Customiser#26]
Map of characters seems like this:
![image](https://user-images.githubusercontent.com/9107312/120065496-dc9c4b80-c071-11eb-9883-d73617341552.png)

The \ character at the very end of line means "next line to be appended here".
So next line is appended - as a part of commentary.
So character  0x5D is not defined - after 0x5C follows the definition od 0x5E. All subsequent characters are off-by-one and if you try to render last character (0x7e), random data occures.

**Comment by tchapi** [comment]
Hi @petrbrouzda 

This seems indeed like a bug, I will issue a fix soon !

**Comment by tchapi** [comment]
This should be fixed with https://github.com/tchapi/Adafruit-GFX-Font-Customiser/commit/8b9c351d821c12791d3267b53c15bd8dbf8e6a89

**Comment by petrbrouzda** [comment]
Thank you.
