### ISSUE TITLE
MyFontIconsGlyphs does not distinguish hexa and decimal numbers

### ISSUE THREAD

**Issue by Nagymadar** [tchapi/Adafruit-GFX-Font-Customiser#29]
Example read in:
const GFXfont MyFontIcons PROGMEM = {
 (uint8_t *)MyFontIconsBitmaps, 
 (GFXglyph *)MyFontIconsGlyphs, 32, 80,  24};

Example output, bug 0x32 and 0x80 instead of 32 and 80:
const GFXfont MyFontIcons PROGMEM = {
 (uint8_t *)MyFontIconsBitmaps, 
 (GFXglyph *)MyFontIconsGlyphs, 0x32, 0x80,  24};

**Comment by tchapi** [comment]
Thanks for the report. I'm quite busy on other projects right now but I'll have a look ASAP !

**Comment by tchapi** [comment]
Hi

https://github.com/tchapi/Adafruit-GFX-Font-Customiser/commit/8bc317623f52e00e51831a521134ef1b60bde569 should fix it. Would you be kind enough to test it ?

Thanks a lot
