### ISSUE TITLE
modifying cols and rows of 8b font messes up the chars

### ISSUE THREAD

**Issue by SunboX** [tchapi/Adafruit-GFX-Font-Customiser#3]
if you create a font with

```bash
./fontconvert xxx.ttf 10 32 252 > xxx10pt8b.h
```

and you try to modify the columns and/or rows (+/-) it messes up the character.

**Comment by clear-sky** [comment]
Hi i tried to add column in my favorite font but all characters after modified font messes up
it does not depend on font and its size!

**Comment by thelevelofdetail** [comment]
Not sure if this is the same issue, but when i try to open and export the font FreeMonoBold12pt7b and then open it again, some characters get messed up. In this case the uppercase letters A and V.
Looking at the Glyphs array it seems like a negative xOffset is causing this Problem.

**Comment by thelevelofdetail** [comment]
I just made a pull request with changes that fixed my issue:
https://github.com/tchapi/Adafruit-GFX-Font-Customiser/pull/6
