### ISSUE TITLE
Create a new Font

### ISSUE THREAD

**Issue by ulrichloose** [tchapi/Adafruit-GFX-Font-Customiser#37]
does not work anymore since 

[Remove yAdvance guessing, parse max glyph height inc. offsets](https://github.com/tchapi/Adafruit-GFX-Font-Customiser/commit/205c5334647ba8d545792488e232641908bcca81)

**Comment by tchapi** [comment]
Good catch.

Does https://github.com/tchapi/Adafruit-GFX-Font-Customiser/commit/8d111c6abe2a996d734a7c0403b420c38d43234f fix it? (it's in `master`)

**Comment by ulrichloose** [comment]
Thank you very much - now it works again!
