### ISSUE TITLE
Can' get it work with fonts created by online "Font Converter"

### ISSUE THREAD

**Issue by dl9sec** [tchapi/Adafruit-GFX-Font-Customiser#4]
Hi,
I created a font at http://oleddisplay.squix.ch with the folowing parameters:
Preview Display: TFT 2.4" (240x320)
Font Family: Monospaced
Style: Bold
Size: 11
Library Version: Adafruit GFX Font
and pasted the output to the "Original font file" text input.
Unfortunately nothing happens if i press "Extract".
I also tried it locally. The test fonts are extracted, but not that (and others I created with the online "Font Converter". The format does't look different from that of the test fonts.

Any ideas?

Regards, Thorsten

**Comment by tchapi** [comment]
Hi
Can you provide the font file you tried ? Are there any errors in the console when you test it ?

**Comment by dl9sec** [comment]
Thanks for the reply.
Attached you'll find two example fonts I created from the genrator that did not work.

The FF-console says:
TypeError: found_size is null                          index.html:214:7

[Fonts.zip](https://github.com/tchapi/Adafruit-GFX-Font-Customiser/files/2624009/Fonts.zip)

**Comment by dl9sec** [comment]
Works perfect now. Great stuff!
Thank you very much :-)
